server:
  port: 8081

spring:
  application:
    name: base-service
  datasource:
    url: jdbc:postgresql://localhost:5432/einstein_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.baseservice.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto